//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CYNetwork
{
	public interface INetEvent
	{
        /**
         * 网络事件错误信息
         * @param err 错误码
         */
        void Error(int status,string errStr);

        /**
         * 接收网络消息事件
         * @param mnCmd     主命令
         * @param sbCmd     子命令
         * @param data      消息数据
         */
        bool HandleReadNetData(ushort mnCmd,ushort sbCmd,CyNetReadBuffer readBuffer);
	}
}

